apiVersion: v1
kind: Service
metadata:
  name: bangun-ruang-service
  labels:
    app: bangun-ruang
spec:
  selector:
    app: bangun-ruang
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
